### ISSUE TITLE
Status on Microsoft.NETCore.DotNetHostPolicy?

### ISSUE THREAD

**Issue by guardrex** [eerhardt/versions#1]
@eerhardt 

I don't see `Microsoft.NETCore.DotNetHostPolicy` in the list. It's resolving to `1.0.1-rc2-002702-00`, so it didn't version with the rest of them to `-24027`, but I need it to get the host executable for my self-contained applications.

Do you know what's going on with that one? ... or did something change to get the correct host executable in published output? Note that my self-contained apps are much leaner by using that with `NETStandard.Library`, like this one for example ...

``` json
"dependencies": {
    "AppExceptionsREST": "1.0.0",
    "ContactLogREST": "1.0.0",
    "CustomMvcRazorHost": "1.0.0",
    "Email": "1.0.0",
    "Microsoft.AspNetCore.Antiforgery": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "StyleScriptInlining": "1.0.0",
    "NETStandard.Library": "1.5.0-rc2-24027",
    "Microsoft.NETCore.DotNetHostPolicy": "1.0.1-rc2-002702-00"
},
```

... I'm avoiding the full `Microsoft.NETCore.App` dep doing it this way.

**Comment by eerhardt** [comment]
@GuardRex - A couple things:
1. The official `versions` repo has been moved to https://github.com/dotnet/versions, and this one `eerhardt/versions` should now be considered deprecated.  I will probably delete it shortly (maybe the end of this week??)
2. The `Microsoft.NETCore.DotNetHostPolicy` package doesn't get built out of the `dotnet/corefx` repo. Therefore, it won't show up under https://github.com/dotnet/versions/tree/master/build-info/dotnet/corefx.  Instead, it gets built out of the `dotnet/cli` repo currently. Show in theory it should show up in https://github.com/dotnet/versions/blob/master/build-info/dotnet/cli/rel/1.0.0-preview1/Latest_Packages.txt.
   - However, that page was manually generated and it looks like DotNetHostPolicy and NETCore.App were never added to it.
3. So to answer your direct question: since DotNetHostPolicy gets built out of the CLI repo, it versions with the CLI. Thus the correct version for the `.NET Core 1.0.0 RC2 - SDK Preview 1` is `1.0.1-rc2-002702-00` (The only one that shows up on [nuget.org](https://www.nuget.org/packages/Microsoft.NETCore.DotNetHostPolicy/1.0.1-rc2-002702-00)).

**Comment by guardrex** [comment]
@eerhardt Excellent! Thank you.
